# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_basis_a <- function(kvec, qvec, thetavec) {
    .Call(`_nbRegQF_get_basis_a`, kvec, qvec, thetavec)
}

get_den <- function(xval, intervalmat, avec, thetavec) {
    .Call(`_nbRegQF_get_den`, xval, intervalmat, avec, thetavec)
}

comp_ll_alpha <- function(alph_c, x_sim_mat, theta_mat_i, f, L, shape, basis_fun, ntimes) {
    .Call(`_nbRegQF_comp_ll_alpha`, alph_c, x_sim_mat, theta_mat_i, f, L, shape, basis_fun, ntimes)
}

get_basis_a_gamma <- function(kvec, qvec, thetavec, shape) {
    .Call(`_nbRegQF_get_basis_a_gamma`, kvec, qvec, thetavec, shape)
}

get_den_gamma <- function(xval, intervalmat, avec, thetavec, shape) {
    .Call(`_nbRegQF_get_den_gamma`, xval, intervalmat, avec, thetavec, shape)
}

get_Mlist <- function(BK_beta, omega_vec, theta_pre) {
    .Call(`_nbRegQF_get_Mlist`, BK_beta, omega_vec, theta_pre)
}

get_mulist <- function(theta_prod, M_list, omega_vec, z, BK_beta) {
    .Call(`_nbRegQF_get_mulist`, theta_prod, M_list, omega_vec, z, BK_beta)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_nbRegQF_mvrnormArma`, n, mu, sigma)
}

sample_basiscoef <- function(mu_list, sigma_list, ntheta) {
    .Call(`_nbRegQF_sample_basiscoef`, mu_list, sigma_list, ntheta)
}

compq_cpp_XZonly <- function(beta_x_post, beta_z_post, Xdesign_quan_post, Zdesign, ntotal, npost) {
    .Call(`_nbRegQF_compq_cpp_XZonly`, beta_x_post, beta_z_post, Xdesign_quan_post, Zdesign, ntotal, npost)
}

compq_cpp <- function(beta_x_post, beta_z_post, rand_post, Xdesign_quan_post, Zdesign, ntotal, npost) {
    .Call(`_nbRegQF_compq_cpp`, beta_x_post, beta_z_post, rand_post, Xdesign_quan_post, Zdesign, ntotal, npost)
}

rcpp_hello_world <- function() {
    .Call(`_nbRegQF_rcpp_hello_world`)
}

